Repository chromaui/storybook-addon-outline, pull requests merged in 2021-06, with the labels that each got.

#9 switch to yarn and 6.3.0-beta
  .github/workflows/release.yml
  package-lock.json
  package.json
  yarn.lock
Labels: minor

#12 Bump Storybook dependencies to 6.3.0
  package.json
  yarn.lock
Labels: dependencies

#13 remove icon from readme
  README.md
Labels: minor

#14 Add default for the outline global value
  src/preset/addDecorator.js
Labels: patch
